DEF_AKINATOR_STATUS(OK,                                     "OK")

DEF_AKINATOR_STATUS(ERROR_IN_DATABASE,                      "ERROR_IN_DATABASE")

DEF_AKINATOR_STATUS(ERROR_MEM_ALLOC,                        "ERROR_MEM_ALLOC")

DEF_AKINATOR_STATUS(ERROR_CANT_READ_DATA_FILE,              "ERROR_CANT_READ_DATA_FILE")

DEF_AKINATOR_STATUS(ERROR_TREE_ERROR,                       "ERROR_TREE_ERROR")
